### ISSUE TITLE
Create content model for blog

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1063]
We'll need the blog listing as well as individual posts

**Comment by kkartunov** [comment]
@ajefts What about following structure?

[contentful-export-blog-update.zip](https://github.com/topcoder-platform/community-app/files/2099878/contentful-export-blog-update.zip)

Please download, unzip and import to review using the cli:
`contentful space import --space-id <DESTINATION_SPACE_ID> --content-file contentful-export-blog-update.json --content-model-only`

The file updates our [TC base config space](https://github.com/topcoder-platform/community-app/blob/new-develop/config/contentful/space.json) with 3 new types:
- Blog
- Blog Post
- Person

Next:
- Do we want/need comments support?
- We will need to create the corresponding containers in community-app code base...do we have some design available?

**Comment by birdofpreyru** [comment]
@kkartunov what is the purpose of _blog_ object? I think, we don't need it. For blog, it is enough to have _Blog Post_ and _Person_ objects. For the listing you can just query _Blog Post_ objects, probably by category/tag, and that's it.

Also, we should be careful with imrpoting test stuff into main Contentful space, as there seems to be no easy way to revert it ;)

> Do we want/need comments support?

I guess, not at the moment: current blog, I believe, does not have this functionality; and the plan should be (i) move existing functionality; (ii) add new one later. Managing comments with Contentful might be not that good, anyway.

**Comment by kkartunov** [comment]
@birdofpreyru yes we can query `Blog Post` objects but we need the `Blog` object as it gives us far more flexibility than it brings confusion in our case. Main reasons to have it are:
- We could support multiple blogs not just one single blog. Say we want at some point community level  blogs or product blogs. Via the `Blog` object we control posts ownership. Otherwise we do not have way to know which post to which blog belongs.
- We can introduce themes, settings and etc. on blog level. We can have fields on the `Blog` object to control the listing(cards/list) whatever we want and have multiple options.
- It is much more convenient/intuitive for the content writer to have `Blog` named X with `Blog Post` objects than regular `Viewport` he/she got used to create for single pages.

> Also, we should be careful with imrpoting test stuff into main Contentful space, as there seems to be no easy way to revert it ;)

Where to import is controlled by the `--space-id` flag. I never suggested testing under "main Contentful space" The export just happens to have the already created types which is fine because it is ready to be merged with the base config.

Regarding comments I also think we better manage them via external service. What I had in mind was to introduce `Identifier/Thread ID` field on the `Blog Post` object to reference. But we can add such functionality latter...

I see now that we should also add `Related Posts` field on the `Blog Post` object. It will allow the writer to pick some related posts and ease us implementing such functionality on the front-side. Updated export here:

[contentful-export-blog-update2.zip](https://github.com/topcoder-platform/community-app/files/2100737/contentful-export-blog-update2.zip)

**Comment by kkartunov** [comment]
Visuals of `Blog Post` and `Person` objects to ease the pain of importing and speed up discussion:
![screenshot from 2018-06-14 06-46-05](https://user-images.githubusercontent.com/5585002/41390722-881aae42-6f9f-11e8-970e-445535688efc.png)
![screenshot from 2018-06-14 06-46-20](https://user-images.githubusercontent.com/5585002/41390727-8c46d52c-6f9f-11e8-867f-df512ad7c882.png)

**Comment by birdofpreyru** [comment]
@kkartunov but, I don't quite see how `Blog` object will make it possible to create a new blog without adding any code to **community-app**? Also, with such approach, people will have to manually add each blog post to a blog object. It might look the same what we do for viewports, etc., but it is, in fact, different, because we assume to have much more blog posts in a blog, than you would have content blocks in a viewport.

I believe, it will be more convenient to select which blog / blogs a post belong to via a drop-down selector in each blog post, that allows to select relevant blogs (or categories) where the post should show up. And to create a new blog, probably with a new style, we just add a bit of code into **community-app**?

**Comment by kkartunov** [comment]
@birdofpreyru we can drop **publish date**. There is `updatedAt` maintained as per [here](https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/common-resource-attributes). It probably gets updated when state change draft -> public.

We always need some code in **community-app** when we add new blog this we can't avoid. But the thing is to avoid model change in Contentful when we do so. We could enforce blog selection via drop-down with limited options in `Blog Post` and then use this filed to fetch posts for particular blog. I also like it more as better solution we win:
- Not need to keep `Blog` object
- Same `Blog Post` can appear on multiple blogs

**Comment by birdofpreyru** [comment]
I guess, `updatedAt` is the time of last update, not necessarily of draft > public state change. But that's fine, we can just show that under **Last updated** label, for most cases it is more useful information than when the post was first published.

Probably, if `revision` equals `1`, then `updateAt` really holds the publish date.

**Comment by kkartunov** [comment]
@birdofpreyru @ajefts Are we agreed on the model structure? Does anyone want to add/remove some fileds or make changes? I want to close this and commit the changes to the TC conf space when we ready...

**Comment by kkartunov** [comment]
Done.
