### ISSUE TITLE
Error: Failed to load RSS feed 

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1124]
Steps to reproduce the above error are:

1. Login accounts.topcoder.com 
2. When a user tried to access dashboard https://www.topcoder.com/my-dashboard 
3. A box popped up saying "Error: Failed to load RSS feed "

@birdofpreyru Please check and fix the issue.

Error console logs:
![image 1](https://user-images.githubusercontent.com/34749364/42744405-fd50625c-88e9-11e8-8b31-bf43b0eb6815.png)

**Comment by birdofpreyru** [comment]
This is also related to #1093, and the root cause is that Topcoder blog was updated without testing of update compatibility with any code that shows some of blog articles, pulling them from blog's RSS. I have updated RSS URL some days ago, but it still does not work remotely (although, works perfectly locally). I suspect this should be a misconfiguration of AWS setup, or nginx.

**Comment by birdofpreyru** [comment]
I have pinged *lazybaer* in Slack about the problem
