### ISSUE TITLE
mm-feature-experiment branch : Add new features on MM details page

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1135]
### Specs
Add support for two new features for MMs

1. Submissions grouped by the handle (I have done some modifications)

These are rough specs, @birdofpreyru @skyhit please do comment on these

#### UI/UX
Omit red blocks from the implementation

![screen shot 2018-07-24 at 7 19 37 pm](https://user-images.githubusercontent.com/683231/43143169-c22c9508-8f77-11e8-97ff-6cb9204642f8.png)

### API Dependency
API support is being implemented here 

https://github.com/appirio-tech/ap-challenge-microservice/issues/420

**Comment by sushilshinde** [comment]
@birdofpreyru we have API support for this submission page. Please assign this task.

![screen shot 2018-08-06 at 5 54 37 pm](https://user-images.githubusercontent.com/683231/43716507-ee682568-99a1-11e8-8f26-5ba628a18f70.png)

**Comment by sushilshinde** [comment]
@birdofpreyru I think submitter changed UI for all types of challenges. Spec was to just use this new UI for MM pages and normalize new data model to old UI. Because Rank and history on the UI doesn't make sense for dev and design.

We need to fix this.

**Comment by birdofpreyru** [comment]
@sushilshinde oh, I understood it that we want to update the tab in similar way for all challenge types (that's also what @ajefts told at some point, that we want to have those expandable rows for all challenges), so that what I asked for the F2F specs

In principle, it makes sense, e.g. this challenge: https://www.topcoder.com/challenges/30068755?tab=submissions where the winner did 3 submissions, in the current prod tab, only one row for the last one is visible, in the updated submission tab, the row can be expanded to see info on all his submissions (though there is a bug with their sorting order).

**Comment by birdofpreyru** [comment]
@sushilshinde just hiding two Rank columns?

**Comment by sushilshinde** [comment]
Yeah

**Comment by birdofpreyru** [comment]
@sushilshinde updated

**Comment by sushilshinde** [comment]
Ok thanks @birdofpreyru  

This is breaking though

https://beta-community-app.topcoder.com/challenges/30068935?tab=submissions

**Comment by birdofpreyru** [comment]
@sushilshinde good catch :) fixed.
