### ISSUE TITLE
TCO tag missing

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1249]
TCO tag is missing in some UI prototype and code track challenges.

Here are the challenges link: 
https://www.topcoder.com/challenges/30069239/?type=develop  

Please fix.

**Comment by birdofpreyru** [comment]
@JayaDhaka I don't get the problem. Of your two links, the first one looks just not TCO-eligible (both the tag under header, and the sidebar link to TCO, are absent consistently). In the second URL, I see both the tag, and the link (but that's not correct, as the challenge is in UI Prototype track, which is deprecated; though I saw discussion elsewhere that it will be fixed in the API layer soon).

**Comment by RiteshTC** [comment]
@birdofpreyru 
This has been resolved. I not related to the code, it was a db thing.
