### ISSUE TITLE
Profile - user consent not prompting

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1279]
**Describe the bug**
I currently have the user consent option turned off and I'm not being prompted when I make any updates to my profile.

**Screenshots**
![image](https://user-images.githubusercontent.com/3812270/45121622-b00cac80-b12f-11e8-8f72-7a0463a0eef8.png)

**Comment by ThomasKranitsas** [comment]
By setting its value I mean either `true` or `false` (any non-empty value). So, `off` (false) is a valid value.

**Comment by ThomasKranitsas** [comment]
Correct. That's the expected behavior based on the current logic.

So, to make it more clear, the first time, the `userConsent` option is missing from the member's traits so the app will prompt the user to choose either yes or no (true/false).
Then it'll save the answer to the `userConsent` property (I believe it's in the personalization trait) and it will never ask again. But both yes and no mean the user has seen the popup and has selected a valid option so we don't need to show the popup again.

**Comment by nithyaasworld** [comment]
@ajefts I am closing this as per the above discussions. Please feel free to re-open if there is still an issue. Thanks.
