### ISSUE TITLE
Fix the size of Blogfeed Component in Contentful

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1680]
Please see [this document](https://docs.google.com/document/d/1RZm1Bqei2flYmR5GJTsPRvaaTs8CRsStosHBs2nmAMQ/edit) for description of issue.

@kkartunov

**Comment by kkartunov** [comment]
> Image 1 can be found here: https://community-app.topcoder.com/examples/contentful/viewport/ZDESwJrkSAOsikiueUiKI

> Image 2 can be found here:
> https://blockchain.topcoder.com/learn

are those same viewports? Can you point me to the name/title of viewport `ZDESwJrkSAOsikiueUiKI`?

**Comment by hokienick** [comment]
Sure!  Here is the viewport: https://app.contentful.com/spaces/b5f1djy59z3a/entries/ZDESwJrkSAOsikiueUiKI

**Comment by kkartunov** [comment]
Those look same to me. Should be as this is same viewport created in Contentful. I think this is not issue but was due to some screen resizing or etc. Check bellow/again and confirm closing this:
![screenshot from 2018-10-17 09-30-48](https://user-images.githubusercontent.com/5585002/47066824-00c3fa80-d1f0-11e8-81ff-b513fbe9e907.png)
![screenshot from 2018-10-17 09-30-45](https://user-images.githubusercontent.com/5585002/47066825-00c3fa80-d1f0-11e8-8935-e10684d11b8a.png)

**Comment by kkartunov** [comment]
@hokienick ^^^

**Comment by hokienick** [comment]
Sorry, thomas made our contentful page live.  Please refer to the doc on what the height should look like.  You can roughly estimate the height that you see there.

**Comment by hokienick** [comment]
No one is really making a fuss about this, so closing this ticket.
