### ISSUE TITLE
[$10] - 'Next Deadline' timer is not working

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#172]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user

- Go to /challenges/30058529

- Click 'View All Deadlines'

- Check the Next Deadline: -

Actual Result(s)
-----------------------------------------------------------------
-  0d 0:0h

Expected Result(s)
-----------------------------------------------------------------
- Must display the timer

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![1](https://user-images.githubusercontent.com/4592712/29667793-5f332e7c-88fb-11e7-95b4-46cb166ddb0f.jpg)

**Comment by birdofpreyru** [comment]
Bug accepted, 1 point.

### Expected Fix
It looks to me that timer does work right when the challenge is active (please double-check in the code), though it shows 00:00 till the next deadline, when the challenge is over. Let's change it for completed challenges to show instead of `Next deadline: ... | Xd XX:XXh until current deadline ends` the text `The challenge is finished`. We still should be able to expand the panel to see all past deadlines of that challenge.

**Comment by shubhendusaurabh** [comment]
assigning myself
