### ISSUE TITLE
[Bug Hunt - NEW BUG]Past challenges is empty and still occupy lots of page space

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#178]
<img width="1658" alt="2017-08-24 9 28 27" src="https://user-images.githubusercontent.com/3046795/29668591-605be574-8913-11e7-966e-fa22f79ead9b.png">

**Comment by birdofpreyru** [comment]
Not a bug. In such situation it does not mean it is empty. It means, it have not found matching past challenges, but it keeps on looking, hence the placeholders (due to api restrictions, it cannot be done in a better way right now). It also dublicates #176 - once that one is fixed, you won't see this.
