### ISSUE TITLE
Repetitive tags of 'Node.js' in subheading of challenge details

### ISSUE THREAD

**Issue by Kvm87** [topcoder-platform/community-app#199]
Steps to Reproduce
1. Login to open http://community-app.topcoder.com/challenges/30058983/?type=develop
2. Observe tags under challenge heading title.

Screenshots : 
![image](https://user-images.githubusercontent.com/20595047/29670696-19ccd5ae-8905-11e7-9087-51d8b98424b1.png)

Expected Result: Only single tag for each unique type is expected.

Current Result: Double tags for 'Node.js' type challenges.

Browser : Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OS : Windows 8.1

**Comment by birdofpreyru** [comment]
Not quite related to Community App, but a good catch, I'll accept it with 3 points.

@ajefts I believe, the reason here is that one of them comes from `platforms` data, and other one from `technologies`. Can we update such labels in the backend to ensure that if the same, like `NodeJS` can be listed in both places, it is listed as exactly the same word (then we can add frontend code to avoid such dublicates when rendering the tags).
