### ISSUE TITLE
[$80] - [Common for Design and Dev challenges] Winner tab is not selected when user click on +X users from 'Past challenges'

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#206]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Scroll down to Past challenges

- Click on +2 in 'RUX - 72H Banking User Interface Design Challenge'

- Observe the opened page and URL: http://community-app.topcoder.com/challenges/30058868/?type=design#winner

Actual Result(s)
-----------------------------------------------------------------
- Winner tab is not selected when user click on +X users from 'Past challenges'

Expected Result(s)
-----------------------------------------------------------------
- Must open the winner tab in the challenge details pages

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by birdofpreyru** [comment]
Accepted, 5 points.
### Note
In general, tabs on the challenge details page are not deep-linkable. We should make them deep-linkable in a neat way. Take, as an example, how it is done to implement deep-linkable filters:
1. If you go to the page printing URL in the browser's URL field, then you do it via server-side rendering (the related Redux reducer's factory checks hash in the HTTP request object, and intialize Redux state accordingly, so that the proper tab is opened by default).
2. When navigated from within the app (from challenge listing in this example). we should pass in related Redux action, to modify Redux state accordingly (to select that tab) before actually going the the challenge details page route with `<Link>`.
3. When we change the tabs, we should update hash part of the URL.

**Comment by daft300punk** [comment]
@birdofpreyru the # part of the url is not sent to the server, so I'm guessing we would not be able to set the state on the server side, unless of course we send the data in some other way. Also, currently, the selected tab(i.e details, registrants etc) is handled by internal react class state and not redux. Handling this with redux state will probably require a large rewrite.

I've tried a different approach. On the client I check for the hash from url, and then change the selected tab if there is a hash part, or show the DETAILS tab by default. What do you think?

**Comment by birdofpreyru** [comment]
@daft300punk I'll prefer to refactor it properly using Redux store. I believe, the amount of work is adequate to the payment: we just need one variable in the store to set the currently selected tab, one action to change it, and a bunch of trivial code to pass these variable and action to the points they need to be checked / dispatched. +That code which will take care about interaction with URL. We can update it to specify the tab as one of the query parameters, rather than hash.

Alternatively, we can refactor the code to have these tabs on different routes, like
/challenges/XXX
/challenges/XXX/checkpoints
/challenges/XXX/winners
etc.
Then we can use react-router's `<Route>` to conditionally render necessary tabs on different routes. But it looks to me, that this might demand more work to make all consistent, than the first option.

**Comment by daft300punk** [comment]
Check out PR - https://github.com/topcoder-platform/community-app/pull/321

**Comment by daft300punk** [comment]
Updated PR - https://github.com/topcoder-platform/community-app/pull/321

**Comment by birdofpreyru** [comment]
OK. Accepted with reduced payment, as the last version of PR demands further enhancements to be ready for merge.
