### ISSUE TITLE
work/language/education profile page V2

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2379]
This is to add some more features to the Work/Language/Education Sections of the Profile Page:

1. Add "Edit" Option to Edit already added Work, Language, Education and Hobby 
3. Add Delete-Confirmation-Popup (just like in Hobbies screen)
4. Add an option to make the End-Date as "Present" for Work-End-Date and Education-End-Date
(This is to indicate that the person is still with that School or the company)
5. Show the validation errors of Work/Language/Education Screen just above the Add button. (Please check Hobbies screen validation-error-location for reference)
6. Make all work/language/education AND HOBBIES fields optional (not required)
7. Under Education: Remove "Type" field, rename "Name" to "Name of College or University" 
8. Make all fields on Devices, Software, Service Providers etc consistent too with the changes we plan to make above

**Comment by nithyaasworld** [comment]
@gurmeetb @Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
@gurmeetb, please help move move this forward. thank you.

**Comment by nithyaasworld** [comment]
@Oanh-and-only-Oanh @gurmeetb  I have also added Hobbies to No:1 above.

**Comment by gurmeetb** [comment]
@Oanh-and-only-Oanh Sure, will get this rolling today.

**Comment by gurmeetb** [comment]
@Oanh-and-only-Oanh @nithyaasworld please see comments inline 

- Add "Edit" Option to Edit already added Work, Language, Education and Hobby
[Guri]: Ok, will get it done

- Add Lookup list for Industry (in Work section) and Major (in Education section)
[Guri]: Let's move this to separate ticket else we will need to wait for V5 Lookup APIs to be ready which we don't know when. 

- Add Delete-Confirmation-Popup (just like in Hobbies screen)
[Guri]: Ok, will get it done

- Add an option to make the End-Date as "Present" for Work-End-Date and Education-End-Date
(This is to indicate that the person is still with that School or the company)
[Guri]: I think we don't need to do this, if we make it Present Date, it will be issue later. Rather a condition check we can put like for Education, if person says `Graduated`, then we make `End Date mandatory else it is optional`. Same way we can add for Work, as `Current Employment` checkbox which makes End Date optional, so we don't send anything to backend. Does that makes sense?

- Show the validation errors of Work/Language/Education Screen just above the Add button. (Please check Hobbies screen validation-error-location for reference)
[Guri]: Actually the way it is done in Hobbies is also not right, we can change it to show error specific to field just below the field for each and make it consistent on all pages - Basic Info, Language, Work, Education, Skills, and Hobbies. Thoughts? 

- Make all work/language/education AND HOBBIES fields optional (not required)
[Guri]: Could you add details why should these be optional ? 

Under Education: Remove "Type" field, rename "Name" to "Name of College or University"
[Guri]: Ok, will get it done

**Comment by Oanh-and-only-Oanh** [comment]
@gurmeetb  @nithyaasworld please see comments inline

Add "Edit" Option to Edit already added Work, Language, Education and Hobby
[Guri]: Ok, will get it done
[Oanh]: Thanks

Add Lookup list for Industry (in Work section) and Major (in Education section)
[Guri]: Let's move this to separate ticket else we will need to wait for V5 Lookup APIs to be ready which we don't know when.
[Oanh]: done

Add Delete-Confirmation-Popup (just like in Hobbies screen)
[Guri]: Ok, will get it done
[Oanh]: Thanks

Add an option to make the End-Date as "Present" for Work-End-Date and Education-End-Date
(This is to indicate that the person is still with that School or the company)
[Guri]: I think we don't need to do this, if we make it Present Date, it will be issue later. Rather a condition check we can put like for Education, if person says Graduated, then we make End Date mandatory else it is optional. Same way we can add for Work, as Current Employment checkbox which makes End Date optional, so we don't send anything to backend. Does that makes sense?
[Oanh]: What if they attended but didn't complete their schooling and have never graduated? Let's have only have Start Year and End Year (or expected).
![image](https://user-images.githubusercontent.com/47536078/58733025-2b8e4800-83a8-11e9-9bd9-8130c259618e.png)
For employment: let's have condition checkbox. If person says "I am currently working in this role", only have State Date (month and year). If person doesn't check the box, have start and end month and year.
![image](https://user-images.githubusercontent.com/47536078/58733149-7f009600-83a8-11e9-9704-2db3078a59b9.png)

Show the validation errors of Work/Language/Education Screen just above the Add button. (Please check Hobbies screen validation-error-location for reference)
[Guri]: Actually the way it is done in Hobbies is also not right, we can change it to show error specific to field just below the field for each and make it consistent on all pages - Basic Info, Language, Work, Education, Skills, and Hobbies. Thoughts?
[Oanh]: Yes, agree

Make all work/language/education AND HOBBIES fields optional (not required)
[Guri]: Could you add details why should these be optional ?
[Oanh]: right now, they can't save a partially completed page. It's either completely filled or empty. It's better if they complete even a few sections of page than an empty page.

Under Education: Remove "Type" field, rename "Name" to "Name of College or University"
[Guri]: Ok, will get it done
[Oanh]: Thanks.

**Comment by gurmeetb** [comment]
@Oanh-and-only-Oanh please see comments below:

Add an option to make the End-Date as "Present" for Work-End-Date and Education-End-Date
(This is to indicate that the person is still with that School or the company)
[Guri]: I think we don't need to do this, if we make it Present Date, it will be issue later. Rather a condition check we can put like for Education, if person says Graduated, then we make End Date mandatory else it is optional. Same way we can add for Work, as Current Employment checkbox which makes End Date optional, so we don't send anything to backend. Does that makes sense?
[Oanh]: What if they attended but didn't complete their schooling and have never graduated? Let's have only have Start Year and End Year (or expected). 
For employment: let's have condition checkbox. If person says "I am currently working in this role", only have State Date (month and year). If person doesn't check the box, have start and end month and year.
[Guri]: `What if they attended but didn't complete their schooling and have never graduated?` - this will be handled with scenario I mentioned above like if user checks `Graduated` checkbox, we make `End Date mandatory` else it stays `optional`. Also, we will rename it to `End Date (or expected)` so users can still push in future date in this optional field. But if they say `Graduated`, End Date will be today or earlier and not in future. 
For `State Date (month and year).` - this will add good amount of work on backend systems, since we might need to also handle migration for users who have already pushed in data or are pushing in while we discuss this feature changes, since we went live with new tabs. So I would suggest we still keep them as MM/DD/YYYY format. This will add no changes to backend for this. 

Make all work/language/education AND HOBBIES fields optional (not required)
[Guri]: Could you add details why should these be optional ?
[Oanh]: right now, they can't save a partially completed page. It's either completely filled or empty. It's better if they complete even a few sections of page than an empty page.
[Guri]: I would suggest we keep logical fields like School Name / Work Name / Hobby as required - main elements still and move others to optional.

**Comment by gurmeetb** [comment]
@Oanh-and-only-Oanh Should we also make all fields on `Devices`, `Software`, `Service Providers` etc consistent too with the changes we plan to make above. 

I am working on detailed specs, will share for review as soon as ready.

**Comment by Oanh-and-only-Oanh** [comment]
@gurmeetb, See inline comments below:

1) Add an option to make the End-Date as "Present" for Work-End-Date and Education-End-Date
(This is to indicate that the person is still with that School or the company)
[Guri]: I think we don't need to do this, if we make it Present Date, it will be issue later. Rather a condition check we can put like for Education, if person says Graduated, then we make End Date mandatory else it is optional. Same way we can add for Work, as Current Employment checkbox which makes End Date optional, so we don't send anything to backend. Does that makes sense?
[Oanh]: What if they attended but didn't complete their schooling and have never graduated? Let's have only have Start Year and End Year (or expected).
For employment: let's have condition checkbox. If person says "I am currently working in this role", only have State Date (month and year). If person doesn't check the box, have start and end month and year.
[Guri]: What if they attended but didn't complete their schooling and have never graduated? - this will be handled with scenario I mentioned above like if user checks Graduated checkbox, we make End Date mandatory else it stays optional. Also, we will rename it to End Date (or expected) so users can still push in future date in this optional field. But if they say Graduated, End Date will be today or earlier and not in future. **[Oanh]- This works.** 

2) For State Date (month and year). - this will add good amount of work on backend systems, since we might need to also handle migration for users who have already pushed in data or are pushing in while we discuss this feature changes, since we went live with new tabs. So I would suggest we still keep them as MM/DD/YYYY format. This will add no changes to backend for this. **[Oanh]- keep as  MM/DD/YYYY format**

3) Make all work/language/education AND HOBBIES fields optional (not required)
[Guri]: Could you add details why should these be optional ?
[Oanh]: right now, they can't save a partially completed page. It's either completely filled or empty. It's better if they complete even a few sections of page than an empty page.
[Guri]: I would suggest we keep logical fields like School Name / Work Name / Hobby as required and move others to optional. 
[Oanh]: School name and Work name can be required. Hobbies and others should be optional as they are not essential information. 

4) Should we also make all fields on Devices, Software, Service Providers etc consistent too with the changes we plan to make above. 
[Oanh]- eventually I'd like these to move to lookup values as well. but yes let's make these fields consistent. Thank you. @nithyaasworld, FYI, we're adding more to the challenge spec.

**Comment by Oanh-and-only-Oanh** [comment]
we need Atif for backend deployment, so holding it. Guri can try to merge to develop, but not confident how the Ci/CD is setup. Hence holding until he is back.

**Comment by gurmeetb** [comment]
@Oanh-and-only-Oanh I am working with Atif on this, found some backend fixes to be done, working on same, we should have it ready soon..

**Comment by gurmeetb** [comment]
@Oanh-and-only-Oanh this has been pushed to DEV - https://www.topcoder-dev.com/settings/profile, I will work with @sushilshinde to keep it there for a day or two tomm so @nithyaasworld can help test this.

**Comment by gurmeetb** [comment]
@nithyaasworld did you had chance to test this ?

**Comment by nithyaasworld** [comment]
Checking this right now!

**Comment by nithyaasworld** [comment]
@gurmeetb I am logged in as dan_developer. I am getting "failed to add user trait" error when trying to edit an existing language or when adding a new language. Please find the screenshot below.

( I am still not done testing this. I will update here once I am done)

This is the API response: {"id":"-3ccef9d9:16b8ab9edb2:-6d85","result":{"success":true,"status":400,"metadata":null,"content":"The following traits already exist:[personalization]"},"version":"v3"}

![image](https://user-images.githubusercontent.com/5114190/60130799-9b300100-97b5-11e9-9244-00c295dc443f.png)

**Comment by gurmeetb** [comment]
@nithyaasworld do you have alternate users to test? Not sure how good is data we have for Dan user, I will send you 2 more users I have over slack - can you try to see if you get same errors for them?

**Comment by nithyaasworld** [comment]
Yes @gurmeetb Same issue with all the users.

**Comment by Oanh-and-only-Oanh** [comment]
hey @gurmeetb, how's this going with the EPOCH formatting?

**Comment by gurmeetb** [comment]
@Oanh-and-only-Oanh @urwithat is helping get that in in sync with ES and DynamoDB....

**Comment by nithyaasworld** [comment]
**P1 Issue:**
- [ ] Not able to add Skills. Getting error as “ERROR: Failed to add user skill!”

**P3 Issues**

- [ ] Profile → Work: When current checkbox is checked, it shows gray shadow under the End Date box. Expectation is, the End Date box should appear non-editable. For that, the field content area should be grayed out and not field’s bottom.

**P4 and Enhancements:**

- [ ] Profile → Work: At a particular scenario, End date becomes editable though “Currently working in this role” checkbox is checked.

     Steps to reproduce:
     - Click Edit of a “Work” entry which has “Currently working in this role” checked
     - Click on any field, example “Company”, remove the already present value for that field
     - Observe that End date becomes editable

- [ ] [Minor] Profile → Work: When just space is entered on Company and then Edit or Add button is pressed, no error message is shown under Company field stating that “Company cannot be blank”
   This is applicable to all mandatory fields of Education and Hobbies too. And also applicable to the Mandatory fields of Basic Info section (First name and Last name)

- [ ] [suggestion] Profile → Work: We can **show the month along with year**. If a person has changed his company in the same year, then it looks like this “2019 to 2019” which doesn’t seem to be looking good.

**Comment by gurmeetb** [comment]
Thanks @nithyaasworld

**Comment by nithyaasworld** [comment]
@gurmeetb I just added a Skill for my profile. Whatever skill I add, it gets added with Verified-Badge. Expectation is, it should not have the verified-badge if the skill is added by the user. 

Can you please check this?

I will meanwhile check the other fixes. Thanks.

**Comment by Oanh-and-only-Oanh** [comment]
released in July.
