### ISSUE TITLE
New Nav Feedback for Version 1

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2663]
**These are observed in https://test-community-app.topcoder-dev.com/**

1. ~Clicking on Compete or Tracks or Explore, not loading the first second-level menu item by default~
2. **When not logged in**, if I navigate to Tracks --> QA, it reloads the whole page. and also nav elements collapsed/expanded state are reset.  Happens with most other menus too.
3. Not logged in state: sub links in the business menu are pointing to the topcoder home page.
4. Business is displayed even for dan_developer user
5. Clicking on Community -> Payments shows 502 error
6. Explore --> TCO is not having New nav
7. Explore --> Forums is not working
8. Explore --> Blog is not having the new nav and also the whole page reloads
9. When navigating between menus, new nav is also re-loaded ( minor issue)
10. When I go to User menu --> Settings, it loads the settings page correctly. But the top nav points to Business.
11. User menu --> Help doesn't have new nav
12. User menu --> About Topcoder doesn't have new nav
13. When I go to any other member's profile page (/members/TonyJ), it loads the member profile page correctly. But the top nav points to Business.
13.a When I go to a challenge details page (challenges/30055052), it loads the page correctly. But the top nav points to Business. .
14. In the NOT logged in state: Community second level menu pages are not having the new-nav as they are redirecting to prod/dev environment.

**Comment by nithyaasworld** [comment]
CC: @Oanh-and-only-Oanh and @sushilshinde

**Comment by nithyaasworld** [comment]
3,4,5,7,10 are important for our Basic release.

**Comment by luizrrodrigues** [comment]
3. https://github.com/topcoder-platform/community-app/issues/2662
4. So main menu Business will works like Switch Button?
5. Payments redirect to DEV site, so error is from DEV site (development don't have payment page)
7. same like 5
10. What will be the default top nav in that case?

**Comment by nithyaasworld** [comment]
4:

> If user is logged into community, **no Business first level menu**
> If user is copilot, tc employee, customer, then "switch to business" in dropdown is enable

5 and 7: Ok, can you please tell me, after deploying this code to production, How can I make sure that Payment and forum links would still work?

10. May be, we should just keep the Community menu expanded with nothing selected. But need confirmation on this from Victor.

**Comment by ya3ya6** [comment]
Hi, i was invonved in `navbar` development , so i think i can give some input.

There is another issue like 10:

13: When I go to `/members/TonyJ`, it loads the member profile page correctly. But the top nav points to Business.

Its because These pages doesn't exists in menu. currently when address doesn't exists in menu, menu will expand with first level 1 menu item (if user is logged in), which is business ([in this line](https://github.com/topcoder-platform/navigation-component/blob/00b6b6f0720976bdd34d4a952a61a5cced3040f2/src/components/TopNav/index.js#L380)).

default menu for the pages that doesnt exists in menu are handled in [this line](https://github.com/topcoder-platform/navigation-component/blob/00b6b6f0720976bdd34d4a952a61a5cced3040f2/src/components/TopNav/index.js#L370), the selected menu for this urls can be handled here (currently only `challenges/30055052` is handled, which will point to right menu. )

**Comment by luizrrodrigues** [comment]
4 - OK
5 and 7 - @sushilshinde we have any test env that support these links?
10 - Ok, let me know.

**Comment by nithyaasworld** [comment]
Thanks @ya3ya6 

13: We have _community --> My Profile_ for /_members/TonyJ_  or are you referring to some other page?

**Comment by ya3ya6** [comment]
@nithyaasworld No prolem. perhaps because that's your profile, so its marked as `My Profile` for you. check another one's profile, like: https://test-community-app.topcoder-dev.com/members/ya3ya6

**Comment by nithyaasworld** [comment]
Got it, Thanks @ya3ya6 I will add this to the original description of this Issue.

**Comment by ya3ya6** [comment]
@nithyaasworld No problem, please also check that `my profile` menu item under community is pointing to right address, because both of https://test-community-app.topcoder-dev.com/settings/profile or https://test-community-app.topcoder-dev.com/members/TonyJ are my profiles.

**Comment by nithyaasworld** [comment]
Yes @ya3ya6, it is working just like what we have now in Production.

**Comment by ya3ya6** [comment]
@nithyaasworld 

14. Not logged in state: When I go to a chellenge details page (`challenges/30055052`), it loads the page correctly. But the top nav points to Business. .

15. Not logged in state:  When I navigate to `community->tracks->design`, and then i navigate to `community->tracks->data science`, the navbar will become collapsed.
The same will happen for navigating from `compete->all challenges` to special challenge.
( It's related to issue #9, because navbar will recreate and it's state will reset.)

16. On mobile: when I choose a sub menu , for example `community -> Tracks`, no page will load, and I should select another sumenu, for example `Competitive programming`. (It may be intended behavior though.)

**Comment by nithyaasworld** [comment]
Thanks @ya3ya6 for reporting!

> Not logged in state: When I go to a chellenge details page (challenges/30055052), it loads the page correctly. But the top nav points to Business. 

Added as 13a

> Not logged in state: When I navigate to community->tracks->design, and then i navigate to community->tracks->data science, the navbar will become collapsed.
> The same will happen for navigating from compete->all challenges to special challenge.
> ( It's related to issue #9, because navbar will recreate and it's state will reset.)

Should be fixed in #2 

> On mobile: when I choose a sub menu , for example community -> Tracks, no page will load, and I should select another submenu, for example Competitive programming. (It may be intended behavior in mobile though.) (The same happens in desktop, but the desktop behavior is probably intended.)

Expectation is, when a first-level menu is clicked, it should auto-load the first Second-level item for the selected first level item. This is #1 in this list.

**Comment by nithyaasworld** [comment]
@luizrrodrigues 

For 10, @Oanh-and-only-Oanh confirmed that we should just keep the Community menu expanded with no selection indicator.

**Comment by Oanh-and-only-Oanh** [comment]
@sushilshinde, can you help with issues #5 and #7 below?
5) Clicking on Community -> Payments shows 502 error. Payments redirect to DEV site, so error is from DEV site (development don't have payment page)
7) Explore --> Forums is not working

**Comment by sushilshinde** [comment]
@Oanh-and-only-Oanh @luizrrodrigues @nithyaasworld  those link should be pointing to, I assume connect dev environment when the build is dev and pointing to production connect if the build is prod. For rest of the links where if there is no corresponding app avail on dev at least URL should form dynamically so if the build is deployed on the beta which will be production build, we should be able to test the whole app on beta.

**Comment by nithyaasworld** [comment]
@luizrrodrigues Closing this  ticket as the issues reported in the description are logged as multiple tickets for your easy tracking.
