### ISSUE TITLE
Clear filters won't reset the 'Sub community' value to All

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#280]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Click 'Filter'

- Set 'Sub community' value to > Topcoder Product Development

- Click 'Clear Filter'

Actual Result(s)
-----------------------------------------------------------------
- Clear filters won't reset the 'Sub community' value to All

Expected Result(s)
-----------------------------------------------------------------
- Clear filters must reset the 'Sub community' value to All

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![51](https://user-images.githubusercontent.com/4592712/29703751-91cbc076-8994-11e7-85a5-346a1139fda9.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
@vic-topcoder need your advice here. Should we consider this selector as a regular filter (i.e. count it inside the Filter switch which opens this panel, reset to all when Clear fitlers is clicked, and save into custom filters)?

**Comment by vic-topcoder** [comment]
@birdofpreyru - the filter can be in 2 pages possible: on a community; or topcoder main site.

- On/within a community, I'd assume the sub community is just a filter within all. Reset filters would clear that (we want to display all challenges from all communities on the main Topcoder website.
- Within a community the filter would represent the space and I'd assume it is always active. Removing the filter would in effect navigate to the main community page → topcoder.com. This one is tricky, and I'd say we should hide it on a sub-community to remove confusion. In a sub-community I'd assume we're listing only the challenges from that particular community, i.e. the filter is applied permanently.

**Comment by birdofpreyru** [comment]
@vic-topcoder Well, option (1) is clear. The (2) we can do really any way you decide:
1. Leave it as it is (as a filter, so that being inside a community you can switch it to see all challenges, or challenges in different community).
2. Doing redirect: if you touch this field, you are actually redirected to the general challenge listing...
3. Hiding it, so that if you are inside community, you just don't see this dropdown at all.
Technically, it is not that hard to do it any way.

**Comment by vic-topcoder** [comment]
Let me discuss this with Tony and team. At this point I guess once you're in a sub-community you don't want to redirect to topcoder necessarily. I'd say hide it for the time being and let's revisit once I have better understanding.

**Comment by ajefts** [comment]
Here is where I'd like to go with it:

1.  For the public listings page, we should show all communities the user has access to.  The default is All and reseting the filter should reset it to All.

2. For sub communities, we should default the filter to the community you are on. I'd also like to keep "Topcoder Public" in the filter. The reason is that it's a valid use case for a hybrid community user to also work on public challenges.  So, I want them to still be able to see all their stuff without leaving the hybrid community.

**Comment by birdofpreyru** [comment]
@ajefts So, in case (1) reset to All, in (2) reset to the opened community?
