### ISSUE TITLE
[$20] - for few second text shown insted of profile image 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#287]
Steps to Reproduce

   
  - Goto http://community-app.topcoder.com/challenges/
  - Scroll down to past challenges 
  - move cursor on any winners(without profile image )
  - observe  

Actual Result(s)
- for few second text shown insted of profile image 

Expected Result(s)
- Should show the image properly 
 
  
Environment

    Device(s): Laptop
    Operating System: Windows 8.1  64bit
    Browser(s): FF 54.0.1

Image/Video/JS Log/Console Log 
https://www.screencast.com/t/TSD7YvAUEly

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

**Comment by daft300punk** [comment]
Is this a browser issue? I don't see it happening in chrome.

**Comment by birdofpreyru** [comment]
@daft300punk It happens only for winners without profile picture, when the default "anonymous man" image is used as the avatar. Can you see it?

**Comment by daft300punk** [comment]
No, I can only see it mozilla, not in chrome. I'm on windows.

**Comment by birdofpreyru** [comment]
I see in Chrome / Ubuntu.

**Comment by elfman** [comment]
@birdofpreyru I'm on Mac, this bug happen in Chrome, not in FF
It seems to be caused by lazy loading image in browser, some browser download the image only when it should be shown on the screen, in that duration there will be only text in the tooltip and the text will be shown on the place where avatar should be.
To fix this, I want to keep the space of avatar before the avatar image loaded. There will still be only text  in tooltip during loading , but the text won't jump when loading finished.
is that OK?
