### ISSUE TITLE
[$20] - Clearing search and search using empty field won't remove the previous search term from the URL

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#329]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- enter '*^&%&^%^&%&(%(%' and search

- Now delete the *^&%&^%^&%&(%(% text and click search

- Page will return to the Challenge listing page but the URL http://community-app.topcoder.com/challenges?%[0]=&%[1]=&^%^=&(%(%=

Actual Result(s)
-----------------------------------------------------------------
- Clearing search and search using empty field won't remove the previous search term from the URL
- http://community-app.topcoder.com/challenges?^^$%^$)(*^=&^=

Expected Result(s)
-----------------------------------------------------------------
- Must clear the search term from URL and display as http://community-app.topcoder.com/challenges

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![63](https://user-images.githubusercontent.com/4592712/29738119-a0015d5a-8a38-11e7-9dca-ec0f7e754100.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
The actual problem here is that when search text is appended to URL special characters are not escaped. As in this example he used `&` in the search string, once it gets to URL, it is treated as params separator, and when filters reseted only known query params are removed, so this string is considered as a bunch of unknown params, and is not removed. We should properly escape the search string, and ensure that search still works properly once it is read from URL.
