### ISSUE TITLE
CI / CD deploy broken

### ISSUE THREAD

**Issue by parthshah** [topcoder-platform/community-app#33]
@birdofpreyru i dug around to figure out why deploys are failing, and builds are essentially timing out. Are there any dependencies that we dont currently need - react-draft-wysiwyg for eg. Mind removing those and giving it a try.

**Comment by birdofpreyru** [comment]
@parthshah `react-draft-wysiwyg` was added to see whether we can use it as an editor for Topcoder Community landing/marketing pages, and there are few test components in the repo depending on it. It used to deploy successfully with this dependency, thus it should not be the root cause of the problem. Actually, between the last successfully deployed commit (71210d4c9054647d2cd9725ed9f8c158008c5992) and the current one there was no big changes, just a few misc small fixes, and update of `autoprefixer` from v6 to v7.

**Comment by birdofpreyru** [comment]
So, I'd say, all dependencies are being used for something in the code. Sure, I can cut something out of the codebase, together with some sample staff (like that editor), but event if it help, it does not seems to be a good solution (basically, we'll run in the same problem as soon as we add a few more dependencies for another reason).

**Comment by parthshah** [comment]
`react-draft-wysiwyg` actually failed to install for locally on more than one instance. But it seems to be passing now. I'm also working on a deploy mechanism, which I hope alleviates some of the problems. Will keep you posted. 
fyi @mtwomey

**Comment by birdofpreyru** [comment]
@parthshah I've cut out everything related to the editor, and, indeed, the App managed to deploy.

**Comment by parthshah** [comment]
I fixed circle.yml to point to the correct deploy script. That should do it.
