### ISSUE TITLE
Issue with "member since" data

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3420]
**Describe the bug**
There are some differences in the "Member since" data between what is shown on frontend and what is in backend data

**To Reproduce**
1. Go to https://www.topcoder.com/members/chok68
2. The profile says 2009 but if we look in informix tables it's actually 2011

**Comment by Oanh-and-only-Oanh** [comment]
This is a data loader issue; the sync of data from informix.

**Comment by RishiRajSahu** [comment]
@Oanh-and-only-Oanh 
**Update 1 -**

- The member since shown on profile page is showing correct value, its in sync with the data we have in OLTP
- Actually the loader which loads data to dynamo is reading this value directly from OLTP instead of DW
- https://github.com/appirio-tech/ap-supply-etl/blob/dev/member-profile/src/main/resources/member-profile-query.sql#L20
- We can close this Git issue

**Update 2 -**
There is wrong data for the field membersince in DW, which I guess is due to some processor sync issue. I will update DW field manually for now this user.

**Comment by Oanh-and-only-Oanh** [comment]
Closing this issue
