### ISSUE TITLE
Remove Subscribe for Newsletter option in Settings page

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3641]
Remove the newsletter subscribe switch in the settings for members since we are not doing the Weekly Newsletters anymore.

**Comment by SathyaJayabal** [comment]
@kkartunov @Oanh-and-only-Oanh , since newsletter preferences were the only section present under email preferences, now the email tab is empty. We should remove the email tab too as it is not a good UX to have an empty tab.

<img width="1440" alt="Screenshot 2020-03-31 at 9 01 12 AM" src="https://user-images.githubusercontent.com/58783823/77984136-6184bb80-732e-11ea-8448-54b16b76a17f.png">

**Comment by kkartunov** [comment]
@SathyaJayabal we need to keep it because of:
1. All other tabs are external and load in new page thus can't begin with new one which breaks tabs.
2. We could add email preferences for general newsletter latter in this section.

Please, feel free to proceed with this one.

**Comment by SathyaJayabal** [comment]
@kkartunov , marking this as pass as per comment above.

**Comment by Jobee1** [comment]
Tested in Beta environment: Only E-mail Preferences is displayed.
![3641](https://user-images.githubusercontent.com/48575864/78216200-03e0a280-74d9-11ea-86ef-79eb4eb022e8.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-04-02 at 5 13 33 PM" src="https://user-images.githubusercontent.com/58783823/78245564-4fa94100-7505-11ea-9a94-66f02f8c4850.png">
