### ISSUE TITLE
Fix HTML in dashboard banner title when collapsed

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3957]
![Screenshot from 2020-02-08 09-35-44](https://user-images.githubusercontent.com/5585002/74081369-ec47e900-4a56-11ea-8838-cc937d5bc7c7.png)

**Comment by kkartunov** [comment]
Test: https://community-app.topcoder.com/my-dashboard?announcementPreviewId=7HYhibSr9lRU8Chz2HNu60

**Comment by SathyaJayabal** [comment]
verified on test env
<img width="1406" alt="Screenshot 2020-02-11 at 2 49 29 PM" src="https://user-images.githubusercontent.com/58783823/74223956-d26c0780-4cdd-11ea-95c2-e7c35909b898.png">

**Comment by SathyaJayabal** [comment]
Still present in production, but fixed in beta. Will close it after verification in production
<img width="1435" alt="Screenshot 2020-02-12 at 1 33 12 PM" src="https://user-images.githubusercontent.com/58783823/74314903-54bb0100-4d9c-11ea-8b31-68a930068b31.png">
<img width="1440" alt="Screenshot 2020-02-12 at 1 33 21 PM" src="https://user-images.githubusercontent.com/58783823/74314912-58e71e80-4d9c-11ea-9372-187320d5f303.png">

**Comment by SathyaJayabal** [comment]
verified in production
<img width="1375" alt="Screenshot 2020-02-12 at 6 22 24 PM" src="https://user-images.githubusercontent.com/58783823/74336633-a8d9db80-4dc4-11ea-886c-12bb1297a4a9.png">
