### ISSUE TITLE
Past Challenges (MMs) are returning empty

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4112]
Steps to reproduce : 1-4 

![Topcoder Challenges 2020-03-14 09-40-13](https://user-images.githubusercontent.com/683231/76674694-384af800-65d8-11ea-89bb-94b2e579312d.png)

Problem # 1 

Calls : https://api.topcoder.com/v4/challenges/?filter=status%3DCOMPLETED&limit=50&offset=750
doesn't include filter `Data Science`

Problem # 2 

UI is not showing challenges even though calls are returning the response.

**Comment by sushilshinde** [comment]
FYI @dmessing

**Comment by dmessing** [comment]
Maybe v5 helps here?

**Comment by LieutenantRoger** [comment]
Hi @dmessing  

We will need to discuss about how to resolve this.

Some background info: in order to resolve this ticket:  https://github.com/topcoder-platform/community-app/issues/3610 we made a configuration time (currently, 30 seconds)  

So if we don't find a result with the filters applied within the configured time above, we would stop continuing to request data, and show user with the `No challenges found in Past Challenge`

**Comment by SathyaJayabal** [comment]
@sushilshinde , this issue is not just with data science track. When we select a date range a few years in the past, the search times out (due to the configured 30 secs).

<img width="1440" alt="Screenshot 2020-05-27 at 11 13 39 AM" src="https://user-images.githubusercontent.com/58783823/82982518-fc86d280-a00b-11ea-85ec-d97f1b8552d0.png">
<img width="1440" alt="Screenshot 2020-05-27 at 11 14 45 AM" src="https://user-images.githubusercontent.com/58783823/82982538-0a3c5800-a00c-11ea-88b1-768364ba36e8.png">
<img width="1440" alt="Screenshot 2020-05-27 at 11 19 31 AM" src="https://user-images.githubusercontent.com/58783823/82982599-29d38080-a00c-11ea-8090-f1ec42e8c8a4.png">

**Comment by Oanh-and-only-Oanh** [comment]
@LieutenantRoger, will this issue be resolved once the new listing performance is upgraded?

**Comment by LieutenantRoger** [comment]
I think so, as long as the V5 API can return past MMs challenges.  

I haven't check the detail, the corresponding requirement seems changed, and the `past challenges` bucket looks should be removed

**Comment by sushilshinde** [comment]
> Yes, I think so, as long as the V5 API can return past MMs challenges.
> 
> I haven't check the detail, the corresponding requirement seems changed, and the `past challenges` bucket looks should be removed

@Oanh-and-only-Oanh is this issue irrelevant now?

**Comment by Oanh-and-only-Oanh** [comment]
I don't want to close this yet until new listing performance is upgraded and this issue is fixed along with it.

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal @sandhiyakavi, please verify if issue is resolved after new listing implementation. thank you.

**Comment by LieutenantRoger** [comment]
This ticket is only for verifying:  so please verify it along with this ticket:  https://github.com/topcoder-platform/community-app/issues/4972

**Comment by SathyaJayabal** [comment]
Will verify along with #4972

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-10-08 at 8 57 24 PM" src="https://user-images.githubusercontent.com/58783823/95479916-ef5df500-09a8-11eb-879f-03b50639d86a.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

![image](https://user-images.githubusercontent.com/55895538/95559605-ffcaaa00-0a52-11eb-9b47-05f3043e1350.png)
