### ISSUE TITLE
Update TC Footer to new design

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4158]
TC Footer should be updated to meet new design https://marvelapp.com/535c9ga/screen/66441662/handoff

**Comment by sandhiyakavi** [comment]
Overlapping occurs with footer in My profile page.

![image](https://user-images.githubusercontent.com/55895538/79186349-55cbe580-7e54-11ea-8bcc-6f21c3a9dbc4.png)

@kkartunov  while clicking on the links in Footer, it is directing to Dev environment pages,is it the expected behaviour? Please clarify my doubt

<img width="959" alt="11" src="https://user-images.githubusercontent.com/55895538/79186384-64b29800-7e54-11ea-83d2-df457e707711.PNG">

**Comment by sandhiyakavi** [comment]
cc: @SathyaJayabal

**Comment by kkartunov** [comment]
@sandhiyakavi yes it is expected links to direct to dev. They are env based and will direct to prod on prod.

I pushed a fix for the overlap issue. Please, re-test when deployment ready.

**Comment by sandhiyakavi** [comment]
Restested the issue. Working as expected

![image](https://user-images.githubusercontent.com/55895538/79194497-9c770b00-7e67-11ea-8d38-e7d03e190201.png)

**Comment by hokienick** [comment]
The youtube link should be: https://www.youtube.com/c/TopcoderOfficial

Also can we remove the tooltip over the social icons?
<img width="597" alt="Screen Shot 2020-04-14 at 9 51 09 AM" src="https://user-images.githubusercontent.com/1373998/79251816-8b150b00-7e35-11ea-9db3-3dfb42340b93.png">

**Comment by SathyaJayabal** [comment]
verified on test env

**Comment by SathyaJayabal** [comment]
[footer.mov.zip](https://github.com/topcoder-platform/community-app/files/4484874/footer.mov.zip)

**Comment by sandhiyakavi** [comment]
Verified on beta Env. working as expected.

[#4158.zip](https://github.com/topcoder-platform/community-app/files/4486521/4158.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-04-16 at 7 48 57 PM" src="https://user-images.githubusercontent.com/58783823/79467622-96299000-801b-11ea-907f-321a0b7682c5.png">
