### ISSUE TITLE
Comcast: Give Back | Challenge Ids

### ISSUE THREAD

**Issue by aaabbott** [topcoder-platform/community-app#4241]
Can we update the challenges displayed on the Give Back page to be the following three challenge IDs from the Comcast group?

- 30122217
- 30122226
- 30122216

**Comment by aaabbott** [comment]
cc @kkartunov

**Comment by kkartunov** [comment]
@aaabbott error with https://www.topcoder.com/challenges/30122226

**Comment by kkartunov** [comment]
cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
30121969 used instead of 30122226 (as there was an error https://github.com/topcoder-platform/community-app/issues/4241#issuecomment-613571037)

Verified on production
<img width="1432" alt="Screenshot 2020-04-15 at 4 03 57 PM" src="https://user-images.githubusercontent.com/58783823/79327828-bc273580-7f32-11ea-9f46-f4c3580a88b7.png">
