### ISSUE TITLE
TC gigs pages

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4788]
Develop www.topcoder.com/gigs according to design https://marvelapp.com/prototype/f0i4ece/screen/72132705.

Pages in scope are:
- https://marvelapp.com/prototype/f0i4ece/screen/72132705
- https://marvelapp.com/prototype/f0i4ece/screen/72094627

Notes:
- on listing page without location and sort dropdowns

QA:
- test URL - https://test-community-app.topcoder-dev.com/gigs

**Comment by SathyaJayabal** [comment]
@kkartunov 

1. URL in main nav does not point not the updated "https://staging-community-app.topcoder.com/gigs". It still points to
"https://staging-community-app.topcoder.com/community/taas". This issue is only present on staging

<img width="1440" alt="Screenshot 2020-08-27 at 9 39 57 AM" src="https://user-images.githubusercontent.com/58783823/91383260-54bab400-e849-11ea-8dc6-79264acaf619.png">

2. The duration, timezone and hours are not displayed for some gigs
3. Required skills are not displayed
4. Description is incorrect
<img width="1440" alt="Screenshot 2020-08-27 at 9 44 03 AM" src="https://user-images.githubusercontent.com/58783823/91383646-46b96300-e84a-11ea-81fe-8b1d70622be1.png">

5. Notes/More info section is repeated
<img width="1440" alt="Screenshot 2020-08-27 at 9 49 32 AM" src="https://user-images.githubusercontent.com/58783823/91383829-baf40680-e84a-11ea-89cf-627fe52fbc6a.png">

**Comment by SathyaJayabal** [comment]
1. Is fixed
2-6 :  Content comes from RecruitCRM that will be updated upon launch.  It currently displays correctly when no data is entered there.
https://topcoder.slack.com/archives/C53KB3T7Z/p1598502587038700

**Comment by SathyaJayabal** [comment]
Verified on Production.
Looks good except for the above 2-6 issues, that will be fixed from RecruitCRM.

<img width="1440" alt="Screenshot 2020-08-27 at 2 59 16 PM" src="https://user-images.githubusercontent.com/58783823/91423270-f3f5a080-e875-11ea-8cc5-0fcfc7bc3e5d.png">
<img width="1440" alt="Screenshot 2020-08-27 at 2 59 25 PM" src="https://user-images.githubusercontent.com/58783823/91423284-f8ba5480-e875-11ea-9f0b-7116b046e877.png">
