### ISSUE TITLE
Update Registration Email in Sendgrid to direct to New 50/50 Page

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4849]
We have an email that goes out to a person after they have registered at Topcoder.  This email is located in SendGrid.  Please update the url to redirect to the url created in Ticket #4847 .

If you need help with this, I can assist.

**Comment by Oanh-and-only-Oanh** [comment]
@mtwomey, please update the url to www.topcoder.com/start

**Comment by mtwomey** [comment]
This is done, but note: This is not a change to sendgrid. This is controlled by the returnUrl param that is in the URI for the registration page (accounts-app). For example, `https://accounts.topcoder.com/member/registration?retUrl=https://www.topcoder.com/start` this will cause the link in the email to be: `https://www.topcoder.com/start`

I changed this for the marketing site (so that non-business user registrations now use that link (above). Meaning this here:

![image](https://user-images.githubusercontent.com/7715262/92978555-bdaf4800-f455-11ea-86c1-3de39842e997.png)

If you click "I'm the talent" you'll get this updated returnUrl. If we want people who register directly via one of the community-app pages to also go here, we need to change the link on the `Register` button in Community-app as well.
