### ISSUE TITLE
Gig work listing page - add dropdowns

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4890]
Scope:
Add location and sort dropdowns and related functionality to gig listing page as per design https://marvelapp.com/prototype/f0i4ece/screen/72092704

**Comment by sandhiyakavi** [comment]
In Sort by dropdown instead of Latest Added Ascending,it is displayed as Latest Added Descending.

![image](https://user-images.githubusercontent.com/55895538/93418438-6130aa80-f8e5-11ea-89ac-1aaee20a71e2.png)

@kkartunov  Needed clarification for the below 

1.  In Marvel app design, I am able to view the information about gig work and FAQ which is not available in the actual implementation.Are those need to be implemeted one?

![image (1)](https://user-images.githubusercontent.com/55895538/93418675-dd2af280-f8e5-11ea-817a-a3cf05b7fb0f.png)
![image (2)](https://user-images.githubusercontent.com/55895538/93418819-2aa75f80-f8e6-11ea-8746-54ae11e2f4e3.png)

2. The user is able to enter text in the dropdown but for sort by textbox sorting happens only if we select from the dropdown.So is the entering text option needed for Sort by textbox?

3. Also the already selected items is not cleared/dimmed if we place the cursor in the textbox (cleared after entering text),Is it expected behaviour?

![image](https://user-images.githubusercontent.com/55895538/93419155-13b53d00-f8e7-11ea-9fb0-6b20acbb1810.png)

4. The dropdown arrow in the dropdowns are not turned into down arrow even if the dropdown is closed.

![image](https://user-images.githubusercontent.com/55895538/93419238-4fe89d80-f8e7-11ea-8a79-41b4947609b8.png)

**Comment by kkartunov** [comment]
@sandhiyakavi @SathyaJayabal 
Please focus on the ticket scope, thank You!
1. We decided to remove that section. The design here is outdated. It is okay to be without as it is currently is.
2. Yes, it is needed. When you type it suggests options to choose from. You need to click on the option to trigger the action. We are good with that.
3. Yes
4. This could be a bug(I can't reproduce it tho') that we will fix in a separate ticket.

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
@kkartunov , there is no way to verify whether the sorting works as the created and updated information is not displayed.
<img width="1440" alt="Screenshot 2020-09-17 at 4 37 21 PM" src="https://user-images.githubusercontent.com/58783823/93462519-15412e00-f904-11ea-8f78-b32c1c4b5c1e.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-17 at 6 27 37 PM" src="https://user-images.githubusercontent.com/58783823/93473376-905e1080-f913-11ea-92df-44e556349dc4.png">
