### ISSUE TITLE
Abandonment Ad Code added to gig pages.

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4912]
Add code snippet to gig listings and gig description pages.

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, please do a hot fix release for this ticket for this Wednesday. It will be a release for this just. @kkartunov is working on the ticket but please have it ready for QA by Tuesday India morning time for @SathyaJayabal to verify.

**Comment by SathyaJayabal** [comment]
verified on test, tracking code present in header for gigs listings and gigs details pages.
<img width="1440" alt="Screenshot 2020-09-15 at 9 07 49 AM" src="https://user-images.githubusercontent.com/58783823/93163136-fab85a80-f733-11ea-8988-7b8db45635ba.png">
<img width="1440" alt="Screenshot 2020-09-15 at 9 08 34 AM" src="https://user-images.githubusercontent.com/58783823/93163145-01df6880-f734-11ea-89b1-ec0b4e5d1ad6.png">

@kkartunov , I see the code snippet added to all the pages. Is his intentional ?

cc @hokienick

**Comment by kkartunov** [comment]
@SathyaJayabal yep, it should be on all pages.

**Comment by SathyaJayabal** [comment]
@kkartunov ,thanks

**Comment by SathyaJayabal** [comment]
verified on staging(develop)
<img width="1440" alt="Screenshot 2020-09-15 at 11 27 52 AM" src="https://user-images.githubusercontent.com/58783823/93171356-8fc44f00-f746-11ea-86f7-b8e5a895e973.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-15 at 4 25 41 PM" src="https://user-images.githubusercontent.com/58783823/93202338-29ecbd00-f770-11ea-9892-179277193b23.png">
