### ISSUE TITLE
Insert Chatbot Script For Gig Pages

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4916]
Please add this script for a chatbot feature on Gig pages only:

```
<script type="text/javascript">
    window._chatlio = window._chatlio||[];
    !function(){ var t=document.getElementById("chatlio-widget-embed");if(t&&window.ChatlioReact&&_chatlio.init)return void _chatlio.init(t,ChatlioReact);for(var e=function(t){return function(){_chatlio.push([t].concat(arguments)) }},i=["configure","identify","track","show","hide","isShown","isOnline", "page", "open", "showOrHide"],a=0;a<i.length;a++)_chatlio[i[a]]||(_chatlio[i[a]]=e(i[a]));var n=document.createElement("script"),c=document.getElementsByTagName("script")[0];n.id="chatlio-widget-embed",n.src="https://w.chatlio.com/w.chatlio-widget.js",n.async=!0,n.setAttribute("data-embed-version","2.3");
       n.setAttribute('data-widget-id','f6584d97-111b-4fd0-635d-c8afb3fb55bd');
       c.parentNode.insertBefore(n,c);
    }();
</script>
```

**Comment by kkartunov** [comment]
@hokienick chatbot window/button overlaps support window/button
![Screenshot from 2020-09-16 08-23-43](https://user-images.githubusercontent.com/5585002/93297768-a0360180-f7fa-11ea-84dc-9d0ae832b760.png)

**Comment by SathyaJayabal** [comment]
@kkartunov , 
1. When we access the gigs pages, the chatbox button is displayed. When we navigate to other pages the chatbox button is still present. It goes away only on refreshing the page. 
Expected behaviour: chatbox button must not be displayed when the suer navigates to other pages.

<img width="1440" alt="Screenshot 2020-09-24 at 10 32 34 AM" src="https://user-images.githubusercontent.com/58783823/94103192-9c852900-fe51-11ea-99c0-9216f8a27faa.png">


2. When we send a message using the chatbox, we see the below message. On closing the chatbox and opening it again, we still see the below message and the user is not able to send another message. Refreshing the page refreshes the chatbox and the user is able to send the message again. Is this the expected bahaviour?
 
<img width="1440" alt="Screenshot 2020-09-24 at 10 33 12 AM" src="https://user-images.githubusercontent.com/58783823/94103197-a0b14680-fe51-11ea-868d-2821f6a4da51.png">

**Comment by ajefts** [comment]
If you can get it installed in an environment again where we can test, we can try some of the chatlio settings to modify the behavior.  For example, this:

![image](https://user-images.githubusercontent.com/3812270/94163350-bc1e5080-fe55-11ea-8aff-6d3877f0feb0.png)

**Comment by SathyaJayabal** [comment]
@ajefts @kkartunov , deployed in qa env now.
https://qa-community-app.topcoder-dev.com/gigs

**Comment by SathyaJayabal** [comment]
@kkartunov @ajefts , please see attached video.
Chatbox is only displayed when we go the gigs pages.  But when we navigate to other pages after visiting the gigs pages, the chatbox is still displayed. 
Expected behaviour : chatbox must be not be displayed when you navigate away from the gigs pages.
[chatbox.mov.zip](https://github.com/topcoder-platform/community-app/files/5286141/chatbox.mov.zip)

**Comment by Oanh-and-only-Oanh** [comment]
@kkartunov, what is needed on this one to move forward?

**Comment by hokienick** [comment]
@Oanh-and-only-Oanh I think we are good for this one according to Tony.  They can control which pages it shows up on now.

**Comment by Oanh-and-only-Oanh** [comment]
can I close the ticket?

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh This one not in prod yet.

**Comment by SathyaJayabal** [comment]
@hokienick, @Oanh-and-only-Oanh, 
I am marking this as qa pass. Here are my observations:
1. Chatbox still present when user navigates away form he gigs pages.
2. New Message indicator does not go away even after user opens the chatbox and sees the message. The indicator is still present even after replying to the message or refreshing the page.
<img width="1440" alt="Screenshot 2020-10-01 at 8 58 05 AM" src="https://user-images.githubusercontent.com/58783823/94762072-56d1de80-03c4-11eb-9a6c-4eb63f854741.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2020-10-01 at 12 46 38 PM" src="https://user-images.githubusercontent.com/58783823/94779329-63662f00-03e4-11eb-9adf-1b1402d053c7.png">
<img width="1440" alt="Screenshot 2020-10-01 at 12 46 54 PM" src="https://user-images.githubusercontent.com/58783823/94779340-695c1000-03e4-11eb-9d8a-3b6d5bfef156.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-10-01 at 7 42 55 PM" src="https://user-images.githubusercontent.com/58783823/94821051-c96fa800-041e-11eb-8da6-e9b5d3e62cfd.png">
