### ISSUE TITLE
Gig job page updates

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4921]
https://marvelapp.com/prototype/f0i4ece/screen/72094627

1. add - Sign Up For Newsletter
2. Forum Link - point link here: https://apps.topcoder.com/forums/?module=ThreadList&forumID=703475

**Comment by sandhiyakavi** [comment]
@kkartunov Needed clarification for below.

I am able to subscribe and subscribed success message is shown.But do we get any mail regarding that?Also if I enter the same Email ID multiple times,it is not showing any error and success message is getting displayed.Is it expected behavior?

[subscribe_gig weekly updated.zip](https://github.com/topcoder-platform/community-app/files/5236349/subscribe_gig.weekly.updated.zip)
[Gig_Forum.zip](https://github.com/topcoder-platform/community-app/files/5236357/Gig_Forum.zip)

**Comment by kkartunov** [comment]
> @kkartunov Needed clarification for below.
> 
> I am able to subscribe and subscribed success message is shown.But do we get any mail regarding that?Also if I enter the same Email ID multiple times,it is not showing any error and success message is getting displayed.Is it expected behavior?
> 
> [subscribe_gig weekly updated.zip](https://github.com/topcoder-platform/community-app/files/5236349/subscribe_gig.weekly.updated.zip)
> [Gig_Forum.zip](https://github.com/topcoder-platform/community-app/files/5236357/Gig_Forum.zip)

Yes, it is expected behavior. There **won't be** a message sent to the email that registers.
This is good to go. Thanks

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2020-09-17 at 4 31 42 PM" src="https://user-images.githubusercontent.com/58783823/93462048-4c630f80-f903-11ea-8a64-59d9530d4175.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-17 at 6 20 20 PM" src="https://user-images.githubusercontent.com/58783823/93472642-92739f80-f912-11ea-94b7-a17cc23878a7.png">
