### ISSUE TITLE
Challenge Listing: challenge timelines are incorrect

### ISSUE THREAD

**Issue by sumitdaga** [topcoder-platform/community-app#496]
https://goo.gl/fkKC5q

**Comment by sumitdaga** [comment]
@birdofpreyru 
I am not sure why you closed this issue ...challenge listing still shows incorrect timelines!!

**Comment by birdofpreyru** [comment]
@sumitdaga It is fixed in the codebase, and you can check it in the dev environment (http://community-west.topcoder-dev.com/challenges, but not that there are many challenges with deadlines very far into future, and that seems to have issues with the correct dates on challenge details page). Will be published to prod some day this week.
