### ISSUE TITLE
Update "change account password" UI

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#5105]
**How to reproduce:**
1) As a logged in user, go to: https://www.topcoder.com/settings/account
2) See that the field for "new passwoard' is automatically filled out. See screenshot
![image](https://user-images.githubusercontent.com/47536078/96015629-a4a30980-0dfc-11eb-9a4d-1b91136a3032.png)

**Expected behavior:**
1) As a logged in user, go to: https://www.topcoder.com/settings/account
2) 'New password' and "re-type new password" fields should be empty
3) When "New password' and "re-type new password" fields are identical, `Change Password` button should activate

**Scope:**
1) "Change Password" functionality is NOT allowed for SSO users such as Topgear, zurich, Credit Suisse, or social media log-ins 

**Testing/Validation**
1. New password CANNOT match current password. 
2. Make sure a password update email is sent to user
3. Make sure member can log in using new password

**Comment by maxceem** [comment]
@Oanh-and-only-Oanh This issue is not reproducible for me.

![image](https://user-images.githubusercontent.com/146016/96018629-2eca8c80-0e54-11eb-874d-8eb06b9840aa.png)

Most likely you are using `LastPassword` Chrome extension which prefills the password for you. Anyway, we can try running a F2F asking participants to find a way to prevent the `LastPassword` to prefill these fields.

**Comment by Oanh-and-only-Oanh** [comment]
You're right. It's the LastPassword extension. no need to run challenge then. Thanks.
