### ISSUE TITLE
TCO21 leaderboards detail results fix

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5132]
Go to https://tco21.topcoder.com/competition-overview/development/leaderboard
Click on any member handle to see detailed results
Try to click on a challenge link

Expected: Link should be properly working
This bug is currently present for many TCO21 leaderboards that have detailed results. All should be fixed by this issue.

**Comment by SathyaJayabal** [comment]
@kkartunov , In production this issue is present for tco21 site and this has been fixed. Please see comparidon   between prod and test env, where the fix is deployed
<img width="1440" alt="Screenshot 2020-11-04 at 11 30 08 AM" src="https://user-images.githubusercontent.com/58783823/98074924-54fead80-1e91-11eb-82c9-c56781e6a8bb.png"> 
<img width="1440" alt="Screenshot 2020-11-04 at 11 29 39 AM" src="https://user-images.githubusercontent.com/58783823/98074915-4f08cc80-1e91-11eb-9ebb-1ffd9fc7bcd6.png">

However, for the tco20 site, this is issue is good in prod, but the issue is  found on the test env, Please see the comparison between the tco20  site on rod and test envs.
<img width="1440" alt="Screenshot 2020-11-04 at 11 29 18 AM" src="https://user-images.githubusercontent.com/58783823/98075001-8ecfb400-1e91-11eb-838e-5ea3ac97a2bb.png">
<img width="1440" alt="Screenshot 2020-11-04 at 11 30 28 AM" src="https://user-images.githubusercontent.com/58783823/98075009-94c59500-1e91-11eb-9e28-db96d97c121e.png">

same with  tco19 site(working on prod , but not on test)

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-11-04 at 2 10 28 PM" src="https://user-images.githubusercontent.com/58783823/98088534-91d59f00-1ea7-11eb-835f-48eea514e4a1.png">

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-11-10 at 1 02 17 PM" src="https://user-images.githubusercontent.com/58783823/98643553-2bdc9200-2355-11eb-9f56-95e86a86074e.png">
<img width="1440" alt="Screenshot 2020-11-10 at 1 02 37 PM" src="https://user-images.githubusercontent.com/58783823/98643574-31d27300-2355-11eb-8095-547d3d85193f.png">

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-11-10 at 7 49 13 PM" src="https://user-images.githubusercontent.com/58783823/98686013-13d53480-238e-11eb-97d1-2fdfd1a8b770.png">
