### ISSUE TITLE
Route password screen updates

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5165]
- ability to change Submit text
- ability trigger the submit with the keyboard return
- stars instead of text as it is a password
- add the possibility for content below form like here https://marvelapp.com/prototype/f94d001/screen/73961104

Test URL: `/wipro-apollo`

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Ready in Stag env.

**Comment by SathyaJayabal** [comment]
@kkartunov,
1. Content below form must be centred
<img width="1440" alt="Screenshot 2020-11-09 at 4 30 38 PM" src="https://user-images.githubusercontent.com/58783823/98533681-4a854f00-22a9-11eb-96d6-f91818cef9e5.png">

2. Suggestion: to have the ability to show password if needed
<img width="263" alt="Screenshot 2020-11-09 at 4 33 03 PM" src="https://user-images.githubusercontent.com/58783823/98533698-4fe29980-22a9-11eb-8bf4-01379b3db323.png">

3. Clarification: User is asked to enter password every time they access the apollo site  even on the same browser session. Is this intentional?

**Comment by kkartunov** [comment]
@SathyaJayabal 
1. updated. It was a content issue
2. no capability for that yet. Good for now without it.
3. Yes, for security reasons.

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-11-09 at 9 18 14 PM" src="https://user-images.githubusercontent.com/58783823/98563371-1cb40080-22d1-11eb-92a6-0473b5cc070a.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2020-11-10 at 12 58 27 PM" src="https://user-images.githubusercontent.com/58783823/98643228-b40e6780-2354-11eb-91fd-9c5a554826d4.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-10 at 7 47 57 PM" src="https://user-images.githubusercontent.com/58783823/98685698-b3de8e00-238d-11eb-8e50-2dea4d69d7a7.png">
