### ISSUE TITLE
Fix "undefined" in challenge Title when shared in Facebook

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5206]
![image](https://user-images.githubusercontent.com/7029641/100044692-89a9b900-2dee-11eb-9508-2fe30aa1581f.png)

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deploying. 

Tool to check: https://developers.facebook.com/tools/debug/

Expected:
Challenge with prize:
> [$200/$100] - Challenge Name

Challenge without prize:
> Challenge Name

**Comment by SathyaJayabal** [comment]
verified
<img width="988" alt="Screenshot 2020-11-24 at 12 23 11 PM" src="https://user-images.githubusercontent.com/58783823/100058783-f2754d80-2e4f-11eb-8ea6-9ef1ca5dda81.png">
<img width="993" alt="Screenshot 2020-11-24 at 12 23 42 PM" src="https://user-images.githubusercontent.com/58783823/100058786-f4d7a780-2e4f-11eb-900b-828ac1ce4b23.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="993" alt="Screenshot 2020-11-24 at 4 56 34 PM" src="https://user-images.githubusercontent.com/58783823/100088444-1c416b00-2e76-11eb-99be-b2be01818099.png">
<img width="986" alt="Screenshot 2020-11-24 at 4 57 01 PM" src="https://user-images.githubusercontent.com/58783823/100088448-1ea3c500-2e76-11eb-8bb2-9c341ffa1b01.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , challenge details page title is displayed instead of challenge name
<img width="985" alt="Screenshot 2020-11-24 at 7 50 28 PM" src="https://user-images.githubusercontent.com/58783823/100106594-be6d4d00-2e8e-11eb-9cfa-865d5f0fae97.png">
<img width="994" alt="Screenshot 2020-11-24 at 7 53 28 PM" src="https://user-images.githubusercontent.com/58783823/100106602-c3320100-2e8e-11eb-9575-aba1aba810de.png">
