### ISSUE TITLE
Gig referrals

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5340]
Integrate referrals for gigs.
https://marvelapp.com/prototype/f0i4ece/screen/77065787

**Comment by SathyaJayabal** [comment]
verified on dev env

gig details page
<img width="1440" alt="Screenshot 2021-02-24 at 8 35 42 AM" src="https://user-images.githubusercontent.com/58783823/108942163-7b349d00-767c-11eb-8949-148749431b5a.png">

gig referral
<img width="660" alt="Screenshot 2021-02-24 at 8 35 09 AM" src="https://user-images.githubusercontent.com/58783823/108942177-825bab00-767c-11eb-90fe-13a3489c9359.png">

how it works page- one of the links is not working
should be `https://www.topcoder.com/thrive/articles/gig-work-at-topcoder-and-faqs` instead of 
`https://www.topcoder.com/thrive/articles/gig-work-at-topcoder`
<img width="1440" alt="Screenshot 2021-02-24 at 8 46 06 AM" src="https://user-images.githubusercontent.com/58783823/108942321-c8187380-767c-11eb-8a36-8f4e80707c25.png">

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2021-02-24 at 11 59 36 AM" src="https://user-images.githubusercontent.com/58783823/108957611-cd36ec00-7697-11eb-813b-5b4b1fefcc05.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-02-25 at 6 45 39 PM" src="https://user-images.githubusercontent.com/58783823/109158812-e031e500-7799-11eb-80ab-e409e1e934ee.png">
<img width="724" alt="Screenshot 2021-02-25 at 6 45 58 PM" src="https://user-images.githubusercontent.com/58783823/109158823-e1fba880-7799-11eb-867f-998171c2df0c.png">
<img width="1400" alt="Screenshot 2021-02-25 at 6 47 34 PM" src="https://user-images.githubusercontent.com/58783823/109158888-f3dd4b80-7799-11eb-98aa-1ae6a86c197f.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-02-25 at 9 06 07 PM" src="https://user-images.githubusercontent.com/58783823/109177171-8509ed80-77ad-11eb-92af-49f9ca594ec1.png">
<img width="1440" alt="Screenshot 2021-02-25 at 9 06 22 PM" src="https://user-images.githubusercontent.com/58783823/109177197-8cc99200-77ad-11eb-9ee4-f7c925ed58e8.png">
<img width="708" alt="Screenshot 2021-02-25 at 9 06 44 PM" src="https://user-images.githubusercontent.com/58783823/109177207-8f2bec00-77ad-11eb-8edd-51e84a72c3cd.png">
