### ISSUE TITLE
Revamp Email Preferences

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5341]
- Switch should reflect whether the user is assigned to that group in Mailchimp.
- **If switch is off**: This means that the user in Mailchimp does not appear in that Mailchimp Group. Clicking the switch so that it turns on should result in that Mailchimp user being added to that Mailchimp Group.
- **If switch is on**: This means that the user in Mailchimp appears in that Mailchimp Group. Clicking the switch so that it turns off should result in that Mailchimp user being removed from that Mailchimp Group
- If user is unsubscribed or "cleaned" in Mailchimp:
  - A message appears at the top:  "You have unsubscribed from Topcoder Emails"
  - If this was a mistake or if you would like to resubscribe, please click the button below.   The button should subscribe the user.
  - All switches should be hidden
- Programs section At this time we only have "Beta Testers".
  - ~~If the user is not in these groups, do not display row on Email Preferences screen.~~

**Comment by SathyaJayabal** [comment]
verified on test
Switch should reflect whether the user is assigned to that group in Mailchimp.
If switch is off: This means that the user in Mailchimp does not appear in that Mailchimp Group. Clicking the switch so that it turns on should result in that Mailchimp user being added to that Mailchimp Group.
<img width="1440" alt="Screenshot 2021-02-09 at 3 35 12 PM" src="https://user-images.githubusercontent.com/58783823/107357521-2fb8b580-6af8-11eb-97bd-0f1d5ee80b76.png">
![Screenshot from 2021-02-09 12-04-22](https://user-images.githubusercontent.com/58783823/107357569-42cb8580-6af8-11eb-9e7e-2c33511fb999.png)

If switch is on: This means that the user in Mailchimp appears in that Mailchimp Group. Clicking the switch so that it turns off should result in that Mailchimp user being removed from that Mailchimp Group
<img width="1440" alt="Screenshot 2021-02-09 at 3 35 37 PM" src="https://user-images.githubusercontent.com/58783823/107357642-5c6ccd00-6af8-11eb-881c-a319c8bc31de.png">
![Screenshot from 2021-02-09 12-04-22](https://user-images.githubusercontent.com/58783823/107357663-6262ae00-6af8-11eb-8253-54733ac46e9c.png)

If user is unsubscribed or "cleaned" in Mailchimp:
A message appears at the top: "You have unsubscribed from Topcoder Emails"
If this was a mistake or if you would like to resubscribe, please click the button below and fill out the form. The button should direct the user to this form.
All switches should be disabled
<img width="1440" alt="Screenshot 2021-02-09 at 3 43 01 PM" src="https://user-images.githubusercontent.com/58783823/107357721-73abba80-6af8-11eb-8cdd-8c43e562aece.png">
<img width="1440" alt="Screenshot 2021-02-09 at 3 58 36 PM" src="https://user-images.githubusercontent.com/58783823/107357741-77d7d800-6af8-11eb-8965-85dcd0502936.png">
<img width="1440" alt="Screenshot 2021-02-09 at 5 01 59 PM" src="https://user-images.githubusercontent.com/58783823/107357805-8c1bd500-6af8-11eb-8ddd-fb3be07593d3.png">

Programs section At this time we only have "Beta Testers".
If the user is not in these groups, do not display row on Email Preferences screen.
<img width="1440" alt="Screenshot 2021-02-09 at 3 38 08 PM" src="https://user-images.githubusercontent.com/58783823/107357831-9a69f100-6af8-11eb-8c7c-8f127f2d05da.png">

**Comment by SathyaJayabal** [comment]
verified on test, works as updated requirements

> * Switch should reflect whether the user is assigned to that group in Mailchimp.
> * **If switch is off**: This means that the user in Mailchimp does not appear in that Mailchimp Group. Clicking the switch so that it turns on should result in that Mailchimp user being added to that Mailchimp Group.
<img width="1440" alt="Screenshot 2021-02-10 at 3 42 32 PM" src="https://user-images.githubusercontent.com/58783823/107496104-ebd8b580-6bb6-11eb-9ee4-0108d8026ba2.png">
![image (21)](https://user-images.githubusercontent.com/58783823/107496121-f1360000-6bb6-11eb-9a2c-8d71baae477a.png)

> * **If switch is on**: This means that the user in Mailchimp appears in that Mailchimp Group. Clicking the switch so that it turns off should result in that Mailchimp user being removed from that Mailchimp Group

<img width="1440" alt="Screenshot 2021-02-10 at 3 42 09 PM" src="https://user-images.githubusercontent.com/58783823/107496160-fabf6800-6bb6-11eb-9bcc-92a42cfa9f4f.png">
![image (20)](https://user-images.githubusercontent.com/58783823/107496185-001cb280-6bb7-11eb-86b1-c556e4647758.png)

> * If user is unsubscribed or "cleaned" in Mailchimp:
>   
>   * A message appears at the top:  "You have unsubscribed from Topcoder Emails"
>   * If this was a mistake or if you would like to resubscribe, please click the button below.   The button should subscribe the user.
>   * All switches should be hidden
![image (18)](https://user-images.githubusercontent.com/58783823/107496255-14f94600-6bb7-11eb-8dca-3251cabd94b0.png)
<img width="1440" alt="Screenshot 2021-02-10 at 3 38 46 PM" src="https://user-images.githubusercontent.com/58783823/107496274-19256380-6bb7-11eb-8522-9e7213996ca5.png">
![Uploading Screenshot 2021-02-10 at 3.42.09 PM.png…]()

**Comment by SathyaJayabal** [comment]
@kkartunov, as we saw in the call unsubscribing from the email, and then resubscribing from the preferences page does not work.

**Comment by kkartunov** [comment]
Yes. @luizrrodrigues please exclude from release.

**Comment by SathyaJayabal** [comment]
@kkartunov , resubscribe works now

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-02-22 at 2 44 27 PM" src="https://user-images.githubusercontent.com/58783823/108688514-051a2400-751e-11eb-8064-75e8b7fca0e3.png">
![image (22)](https://user-images.githubusercontent.com/58783823/108688529-08adab00-751e-11eb-9559-8335b27d9fab.png)

<img width="1440" alt="Screenshot 2021-02-22 at 2 46 27 PM" src="https://user-images.githubusercontent.com/58783823/108688543-0d725f00-751e-11eb-84d5-b1d87ac91025.png">
![image (23)](https://user-images.githubusercontent.com/58783823/108688557-106d4f80-751e-11eb-8bdb-d6f3a571b6b2.png)

<img width="1440" alt="Screenshot 2021-02-22 at 2 48 05 PM" src="https://user-images.githubusercontent.com/58783823/108688579-16fbc700-751e-11eb-875d-e8be68015530.png">
![image (24)](https://user-images.githubusercontent.com/58783823/108688591-1bc07b00-751e-11eb-8aa5-8d77d52165cd.png)

<img width="1440" alt="Screenshot 2021-02-22 at 2 48 46 PM" src="https://user-images.githubusercontent.com/58783823/108688627-23801f80-751e-11eb-87ea-229e59f42693.png">
![image (25)](https://user-images.githubusercontent.com/58783823/108688641-267b1000-751e-11eb-82d2-725c6ebcbb97.png)

**Comment by SathyaJayabal** [comment]
verified on prod by @kkartunov
