### ISSUE TITLE
Community App doesn’t shows a user as registered after registration

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/community-app#5352]
Register to a challenge.
Registration email is received but submit button is not enabled. 
Discussion forums tab is not visible as well.

**Comment by sushilshinde** [comment]
@RiteshTC can you please provide examples?

**Comment by RiteshTC** [comment]
@sushilshinde Screenshot received from the member shared in PDC channel.
Another one using my user Registration complete but there is no discussions tab.
<img width="1325" alt="Screen Shot 2021-02-16 at 12 57 39 PM" src="https://user-images.githubusercontent.com/5771673/108031346-b6204a80-7056-11eb-8d76-c886e15af76b.png">

**Comment by sushilshinde** [comment]
any other example?

**Comment by rootelement** [comment]
@RiteshTC please test again. I deployed a temporary fix allows me to register for the screenshotted challenge above.

**Comment by SathyaJayabal** [comment]
@RiteshTC , there were two issues.
1. User's registration not showing up in challenge details page. This should be fixed by @rootelement 's temp fix.
2. The challenge discussion link not displayed, for the screenshot you have above
https://www.topcoder.com/challenges/9ffff72c-ad6a-4c70-b0bf-ac52fd049558?tab=registrants
It looks like the forum was not created for this challenge. Lets move this issue to the forums repo.

**Comment by rootelement** [comment]
There's a chance it was related from the forum-processor. Please cross-link the thread here. I'll talk to @jmgasper too
