### ISSUE TITLE
Challenge Details : Wrong start time.

### ISSUE THREAD

**Issue by lijulat** [topcoder-platform/community-app#541]
In the new challenge details page the challenge start is always showing up as current date time on iOS Safari browser

**Comment by birdofpreyru** [comment]
@lijulat Can you provide a screenshot? Does it happen in the collapsable panel with phase deadlines in the challenge details header? If so, I am a bit puzzled, cause if the related code is browser-dependent (it does not look that for me at the first glance), then it should screw times shown in other places as well, which you don't experience, I guess?

**Comment by lijulat** [comment]
![4267db55-fcd9-4f01-abc4-062e995d85d7](https://user-images.githubusercontent.com/17545227/32276715-3c938dc6-bf10-11e7-8b20-6ead1d0f28db.png)

**Comment by lijulat** [comment]
@birdofpreyru check the start time of the challenge in the screenshot above .

**Comment by birdofpreyru** [comment]
### Expected Fix:
To get reward for this ticket, it is necessary to double-check, whether the problem is still present, and if yes to solve it, and comment briefly what was the issue, if it won't be obvious from the code.

**Comment by arun1595** [comment]
@birdofpreyru I confirmed that we're indeed displaying the `registration` phase's `actualStartTime` or `scheduledStartTime` as the challenge start time in the DeadlinesPanel.

The only case when **user's current time** is displayed as the challenge start time is if the first phase(`type` - `Registration`)'s `actualStartTime` and `scheduledStartTime` are both `undefined`. In that case, `moment(undefined)` returns the user's current time.

```js
// DeadlinesPanel/Card/index.js

let start = deadlines[0]; // Registration phase
start = start.actualStartTime || start.scheduledStartTime; // undefined

// DeadlinesPanel/Card/index.js

const time2 = moment(time); // time is `undefined`, `moment(undefined)` => user's current time
```

Won't the challenge creators provide either `actualStartTime` or `scheduledStartTime` for the Registration phase? If they had, we wouldn't have faced this issue.

I am not sure how the backend for challenges is implemented, shouldn't `actualStartTime` and `scheduledStartTime` fields be required?


Sidenote: The [challenge in the screenshot](https://www.topcoder.com/challenges/30060086/?type=develop) displays the right start time(I guess the challenge creators updated the start time after this issue was reported). Btw, I tried to look for challenges in production which suffer from the same issue but couldn't find any.
