### ISSUE TITLE
Social share thumbnail images for challanges

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5447]
Thumbnails images have been designed and added here: https://drive.google.com/drive/folders/1JCV5upiISO8AWfwAhIZy3JnDjuXANro-?usp=sharing

**Comment by SathyaJayabal** [comment]
@kkartunov , I can see the image updated for design and dev contests. But for Qa and DS challenges I see the dev image instead of the Qa and DS  images
Design:
<img width="1271" alt="Screenshot 2021-04-28 at 5 08 33 PM" src="https://user-images.githubusercontent.com/58783823/116399972-1dbcf800-a847-11eb-9d78-927fa631f3d5.png">
Dev
<img width="1254" alt="Screenshot 2021-04-28 at 5 09 58 PM" src="https://user-images.githubusercontent.com/58783823/116399992-244b6f80-a847-11eb-9bc7-7cd666cffbaf.png">

QA
example contests:
https://staging-community-app.topcoder.com/challenges/991bd7fd-de20-45fd-b4d3-55a7174ea4e4
https://staging-community-app.topcoder.com/challenges/e93cb369-4c82-458a-af08-517e76baeac6
<img width="1253" alt="Screenshot 2021-04-28 at 5 25 39 PM" src="https://user-images.githubusercontent.com/58783823/116400005-29a8ba00-a847-11eb-9710-e1264d10bfc3.png">
DS
example contests
https://staging-community-app.topcoder.com/challenges/6e595f59-86a1-455b-8f98-c172d1f38dd0
https://staging-community-app.topcoder.com/challenges/39f57908-803c-4b69-b208-4fc03717ab12
<img width="1255" alt="Screenshot 2021-04-28 at 5 26 57 PM" src="https://user-images.githubusercontent.com/58783823/116400024-2f060480-a847-11eb-8611-df0115ee8509.png">

**Comment by kkartunov** [comment]
@SathyaJayabal those issues found are fixed. Please, re-test, thanks!

**Comment by kkartunov** [comment]
@SathyaJayabal it is now deployed on **beta**

**Comment by sandhiyakavi** [comment]
@kkartunov For below QA and DS challenge which has prize amount $0 , the images are not loading
https://beta-community-app.topcoder.com/challenges/48406f89-3b18-488e-bccf-b7c7e6e8dd0b
![image](https://user-images.githubusercontent.com/55895538/117103104-ab9f6280-adb4-11eb-8be7-a5c4f0a6d04f.png)

https://beta-community-app.topcoder.com/challenges/118cb7f0-25e9-40e5-83ee-bd6fb3514e1d
![image](https://user-images.githubusercontent.com/55895538/117103197-d7bae380-adb4-11eb-9ef0-a4d69867797d.png)

But for other QA and DS challenges, its loading fine

QA Challenges:
![image](https://user-images.githubusercontent.com/55895538/117102240-e30d0f80-adb2-11eb-9874-35bb22512937.png)
DS challenge:
![image](https://user-images.githubusercontent.com/55895538/117103374-384a2080-adb5-11eb-8d52-3b73b887a9de.png)

Design challenges:
![image](https://user-images.githubusercontent.com/55895538/117102071-7abe2e00-adb2-11eb-9f78-e5cf48ded6ae.png)

Dev challenges:
![image](https://user-images.githubusercontent.com/55895538/117101864-1602d380-adb2-11eb-902e-f91f96e913d0.png)

**Comment by sandhiyakavi** [comment]
Verified on Staging Env.

<img width="960" alt="F2F_thunmb" src="https://user-images.githubusercontent.com/55895538/117387797-7d409500-af24-11eb-8f31-aa9cba6cf5bd.png">
<img width="960" alt="challenge_thumb" src="https://user-images.githubusercontent.com/55895538/117387810-80d41c00-af24-11eb-9b06-5a4602dbcea5.png">
<img width="960" alt="QA_thumnail" src="https://user-images.githubusercontent.com/55895538/117387815-83367600-af24-11eb-858a-c700ae75b69d.png">
<img width="960" alt="ds_thumnail" src="https://user-images.githubusercontent.com/55895538/117387825-8598d000-af24-11eb-940d-54e63bf91ebf.png">
<img width="960" alt="design_thumnail" src="https://user-images.githubusercontent.com/55895538/117387833-87fb2a00-af24-11eb-8d9c-7c0d56880c16.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected

<img width="956" alt="thumb_1" src="https://user-images.githubusercontent.com/55895538/117416836-bc86da00-af54-11eb-917b-0f85003c6bad.png">
<img width="958" alt="thumb_2" src="https://user-images.githubusercontent.com/55895538/117416845-bee93400-af54-11eb-8afa-95f7eb0fa997.png">
<img width="960" alt="thumb_3" src="https://user-images.githubusercontent.com/55895538/117416860-c1e42480-af54-11eb-8457-1249ff3d89ba.png">
<img width="958" alt="thumb_4" src="https://user-images.githubusercontent.com/55895538/117416870-c4467e80-af54-11eb-9c39-bdde95634e9c.png">
<img width="960" alt="thumb_5" src="https://user-images.githubusercontent.com/55895538/117416882-c6a8d880-af54-11eb-9a32-f7f829933544.png">
