### ISSUE TITLE
Thrive filter - authors update

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5521]
-  replace default text in the dropdown with "Type author name or handle"
https://monosnap.com/file/6MwIRAtI98fJUzPkaKbk5hFcYoYknD
- switch from names to TC handles for the authors dropdown. Apply only if author's handle is set in Contentful, if not fall back to names as it is currently

**Comment by sandhiyakavi** [comment]
@kkartunov Track -->Competitive programming/Data Science/Design/Development/QA loading continuously in both QA as well as Dev Environment.

<img width="960" alt="dev_env_thrive" src="https://user-images.githubusercontent.com/55895538/119607605-93f55000-be2f-11eb-8ca0-af624697053a.png">

![image](https://user-images.githubusercontent.com/55895538/119607774-dcad0900-be2f-11eb-80b7-0607f289523e.png)

**Comment by kkartunov** [comment]
@sandhiyakavi this looks to be env issue. Deploying that to beta for QA now...

**Comment by sandhiyakavi** [comment]
@kkartunov If we click "clear Filters" to clear the filter, "All Authors" is displayed as default in Authors field.

![image](https://user-images.githubusercontent.com/55895538/119620730-49300400-be40-11eb-8e72-5325d436f2d8.png)

https://user-images.githubusercontent.com/55895538/119620693-3d444200-be40-11eb-8304-e31a637a8269.mp4

Other things are good.
"Type author name or handle" is displayed as default text.

![image](https://user-images.githubusercontent.com/55895538/119620409-ea6a8a80-be3f-11eb-8892-9dc043a288c3.png)

userhandle displayed instead of author's name.
![image](https://user-images.githubusercontent.com/55895538/119620471-fc4c2d80-be3f-11eb-9a76-d447a6e9ca67.png)

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-05-28 at 7 49 46 PM" src="https://user-images.githubusercontent.com/58783823/119998177-188dcd00-bfee-11eb-9750-fc18216646b3.png">
<img width="1440" alt="Screenshot 2021-05-28 at 7 50 05 PM" src="https://user-images.githubusercontent.com/58783823/119998207-1f1c4480-bfee-11eb-8a71-9f2772be3cf0.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-28 at 9 43 06 PM" src="https://user-images.githubusercontent.com/58783823/120012938-c9e82f00-bffd-11eb-9106-d52950801060.png">
<img width="1440" alt="Screenshot 2021-05-28 at 9 43 33 PM" src="https://user-images.githubusercontent.com/58783823/120012954-cf457980-bffd-11eb-8b94-ef63b9324344.png">
