### ISSUE TITLE
Disable download of infected submissions

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#6059]

**Comment by codejamtc** [comment]
Submission Review page UI change  

- Dev Environment - We have some issues so we can’t test the message very effectively because of the failing submission api


https://user-images.githubusercontent.com/42398485/160812206-513a1e77-0100-492f-b107-c7fca0b968bc.mp4


**In Staging**  

In the Community Submission page we will see Scanning... when the submission is in scanning and then if it is an invalid submission we will see Malware found in submission https://staging-community-app.topcoder.com/challenges/5d3e94be-8eaf-4a40-a855-a9a858b71cfd/my-submissions

![bandicam 2022-03-30 15-48-13-958](https://user-images.githubusercontent.com/42398485/160812016-ff9e0c92-b131-408f-b718-87b106b5fc6a.jpg)

When we check the submission in the Submission review app https://submission-review.topcoder.com/challenges/30253018/submissions/ba896f7e-2bbb-4775-a947-b6ff34d369b5 it will display (Malware found in submission) 

![bandicam 2022-03-30 15-47-58-221](https://user-images.githubusercontent.com/42398485/160811948-814a940d-3430-4c60-bced-a022aa22a2e0.jpg)

https://user-images.githubusercontent.com/42398485/160812180-48e88e0e-1438-4a9e-9542-1e343b6a6f17.mp4
