### ISSUE TITLE
Make challenge spec pages editable

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#636]
- markdown editor
- edit inline
- easily preview

**Comment by ajefts** [comment]
@birdofpreyru Here are some issues to work out.

- Default to markdown view.
- Insert image button is not doing anything when in markdown view
- Remove the Highlight button
- The "Inline Markdown" button is always inactive for me.  Can we just remove it?
- When I save in prod, I'm just getting a blank screen returned and the data doesn't seem to be actually saving.

**Comment by birdofpreyru** [comment]
@ajefts 
The marked fixes are pushed into prod; with the buttons in Markdown mode it is tricky due to MD nature: it makes all actions non local to the cursor position / selection, as it is necessary to analyse and correctly update the markup around the selection to properly update the style, and for many things there are alternative markups. I would say, may be we just hide all these text styling / insert image buttons in the MD mode?

**Comment by ajefts** [comment]
I'm ok hiding the buttons in markdown mode...

@cwdcwd hoping you can help with this one in a couple weeks...  We have a version in prod, but still needs some work...
