### ISSUE TITLE
The "View more challenges" button is not working. ...

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#690]
The "View more challenges" button is not working. Please fix!! Thanks. (See https://www.topcoder.com/challenges/?bucket=openForRegistration and scroll down to see the button.)

**Comment by birdofpreyru** [comment]
@ThomasKranitsas I have checked, this bug was introduced when your merged in the reviews opportunities code into *develop*. I see that `expanded` prop is not passed into the listing buckets anymore, so it becomes always `false` by default in each bucket, thus when `View more challenges` buttons is clicked, the bucket does not expand.
