### ISSUE TITLE
TC header and footer

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#7]
Topcoder header and footer should be copied into this repo, to be used in TC pages served from here.

**Comment by birdofpreyru** [comment]
@vic-topcoder What these should be?
I see that in `react-components` there is a footer of the same style like the one in prod now (though, spacings, font sizes, etc. are a bit different), and there is something looking like a new version of header:
![scr-12](https://cloud.githubusercontent.com/assets/20144632/24858653/760d63d4-1ded-11e7-90db-621395881534.png)
What should we do? Should we take the footer from `react-components` and port the header from prod to react? Or should we start using the new header right away? Or, do you have completely another idea about them?

**Comment by vic-topcoder** [comment]
We use slightly different footers on Connect and Topcoder due to the nature of the apps. The header actually is top navigation, which again is different for the apps. Ideally the top navigation would share some similarities between the apps, but I'd say both are custom components for each app.

Ideally we'll reuse the sub-components from the nav - search, tabs, logged out/logged in avatar, logo navigation, filters. The difference is that the nav would provide context for the included components to render with different color theme - that's why I wanted to use (react themr)[https://github.com/javivelasco/react-css-themr] to provide different CSS per sub-components in that exact case - white labeling of the app. This would allow us to pass different themes for the sub-components on header and footer to adapt to different apps.

Footer is another component that should be app specific, but reuse sub-components. We have links mostly, copyright, and sometimes social. Depending on the layout, we have different footers, and on the community (topcoder) app I want to change the layout.

Hope this makes sense and helps.

**Comment by birdofpreyru** [comment]
UPDATE: Is addressed in this F2F: https://www.topcoder.com/challenge-details/30057239/?type=develop (Header and Footer from Topcoder Community website it prod will be copied into `community-app` to use in the new pages. It is to prepare new pages for public release asap. Fancy theming staff will be addressed later.).

**Comment by birdofpreyru** [comment]
UPDATE: F2F didn't work out, I've ported TC header and footer myself (turned out to be quite more work, than anticipated, as the header is interactive and basically had to be rewritten to use the Redux store for its state). As of commit 5dd50e4632df1651ec593a966ea17dea20d6ee52, the SMP can be safely released to prod, though some header/footer-related code enhacements and unit tests are still to be added, thus not closing the ticket.

**Comment by ajefts** [comment]
Thanks!
