### ISSUE TITLE
Unable to join or register

### ISSUE THREAD

**Issue by vbhatia9** [topcoder-platform/community-app#762]
Getting an error when trying to register my name , vbhatia9

**Comment by RiteshTC** [comment]
@birdofpreyru can you please check this. 

This issue is being reported by a lot of users. I don't have specific details but can provide some handles like jkeam, dubeynidhi007 who face this issue continuously.
It looks like the registration succeeds, but the registration button doesn't change the status.

A subsequent clicking on the register button, raises the error 400, you have already registered on the challenge.

We may need to notify the user, the registration is successful.

**Comment by birdofpreyru** [comment]
:point_up: @sushilshinde I guess, this also related to what we discuss in our email thread about API / ES, etc.

**Comment by RiteshTC** [comment]
cc: @cwdcwd

**Comment by m-yadav** [comment]
copilot reported user facing registration issue in the following challenge https://www.topcoder.com/challenges/30088501

Console shows a 500 status with message : failed to create the forum wrapper

But the user is registered and can be seen once the user does a hard refresh. 

![error](https://user-images.githubusercontent.com/45197181/56183946-09c64500-6036-11e9-86de-840e88beeef5.png)
