### ISSUE TITLE
Error when trying to access private challenge

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#801]
When a challenge is restricted by a group(s) and you aren't logged in or don't have permission, it's responding with a default error message.  

![image](https://user-images.githubusercontent.com/3812270/37795055-b6e991fe-2de9-11e8-86b9-5fc0249f2f95.png)

We should change this so it presents a friendly message and asks the user to login/join the community like we do on the /challenges page

![image](https://user-images.githubusercontent.com/3812270/37795171-0c58c04c-2dea-11e8-8673-cfc18f2fbc57.png)

**Comment by ajefts** [comment]
@birdofpreyru can we get this one out to the community?

fyi @cwdcwd

**Comment by birdofpreyru** [comment]
@ajefts @cwdcwd to make it in a universal way, it would be helpful if api, in addition to rejecting the request to fetch challenge details, would also return group IDs that allow access to the challenge. Then it would be possible to figure out, which community that challenge is relevant to, whether the user can self-join that communty (we should double-check, whether groups expose self-join flag via api to get their details), and thus show the correct image like you say, or a better un-auth message otherwise.
